#! /bin/sh
#
# Script called by the DC-API batch plugin to pack the input fiels
#
# Usage:
#	batch_pack <srcdir> <dstfile> <pattern> [<pattern>...]
#
# Where:
#	<srcdir>	base directory where all the source files live
#	<dstfile>	where to put the pack
#	<pattern>	shell pattern of filest to be included under <srcdir>

SRCDIR="$1"
shift
DSTFILE="$1"
shift

exec tar -C "$SRCDIR" -c -z -f "$DSTFILE" "$@"
