debian/tmp/usr/sbin/3g-bridge
debian/tmp/usr/sbin/wssubmitter
debian/tmp/usr/sbin/wsmonitor
debian/tmp/usr/bin/injector
debian/tmp/usr/lib/3g-bridge/*.so
debian/tmp/usr/share/java/*.jar
debian/3g-bridge.conf			usr/share/3g-bridge
db/schema.sql				usr/share/3g-bridge
examples/batch_pack			usr/share/3g-bridge
examples/batch_unpack			usr/share/3g-bridge
examples/dc-api.conf			usr/share/3g-bridge
debian/master.xml			usr/share/3g-bridge
