#! /bin/sh
#
# Script called by the DC-API batch plugin to unpack the output files
#
# Usage:
#	batch_unpack <srcfile> <dstdir>
#
# Where:
#	<srcfile>	the packed output file
#	<dstdir>	base directory where to unpack the files

SRCFILE="$1"
DSTDIR="$2"

exec tar -C "$DSTDIR" -x -z -f "$SRCFILE"
