/*
 * Schema description for CancerGrid job database
 */
drop table if exists cg_job;
drop table if exists cg_inputs;
drop table if exists cg_outputs;

/*
 * Job table
 */
create table cg_job (
    id			char(36)     not null	/* Unique job id, generated by the submitter */,
    alg			char(32)     not null	/* Algorithm (executable) name */,
    status		char(10)     not null	/* Status of job [INIT, RUNNING, FINISHED, ERROR, CANCEL] */,
    gridid		varchar(254)	 	/* Job's grid identifier */,
    args		varchar(254)		/* Command-line arguments to be passed to the algorithm at job execution */,
    property		varchar(254) 		/* Cancergrid specific job settings */,
    dsttype		varchar(254)		/* Destination type */,
    dstloc		varchar(254)		/* Destination location */,
    creation_time	timestamp    null default current_timestamp /* Creation time of job descriptor */,
    primary key (id)
) type=InnoDB;


/*
 * Job input table
 */
create table cg_inputs (
    id                  char(36)     not null /* Unique id of job, foreign key of job.id */,
    localname           varchar(254) not null /* Basename of the file */,
    path		varchar(254) not null /* Absolute path of the file */,
    primary key (id)
) type=InnoDB;


/*
 * Job output table
 */
create table cg_outputs (
    id                  char(36)     not null /* Job's identifier */,
    localname           varchar(254) not null /* Basename of the file */,
    path		varchar(254)          /* Expected absolute path of the file */,
    primary key (id)
) type=InnoDB;
