/*
 * Schema description for CancerGrid job database
 */
drop table if exists cg_job;
drop table if exists cg_inputs;
drop table if exists cg_outputs;
drop table if exists cg_algqueue;

/*
 * Job table
 */
create table cg_job (
    id			char(36)     not null	/* Unique job id, generated by the submitter */,
    alg			char(128)    not null	/* Algorithm (executable) name */,
    grid		varchar(254) not null	/* Target grid name */,
    status		char(10)     not null	/* Status of job [INIT, RUNNING, FINISHED, ERROR, CANCEL] */,
    gridid		varchar(254)	 	/* Job's grid identifier */,
    args		varchar(254)		/* Command-line arguments to be passed to the algorithm at job execution */,
    creation_time	timestamp    null default current_timestamp /* Creation time of job descriptor */,
    primary key (id)
) type=InnoDB;


/*
 * Job input table
 */
create table cg_inputs (
    id                  char(36)     not null /* Unique id of job, foreign key of job.id */,
    localname           varchar(254) not null /* Basename of the file */,
    path		varchar(254) not null /* Absolute path of the file */,
    primary key entry (id, localname),
    foreign key (id) references cg_job(id) on delete cascade
) type=InnoDB;


/*
 * Job output table
 */
create table cg_outputs (
    id                  char(36)     not null /* Job's identifier */,
    localname           varchar(254) not null /* Basename of the file */,
    path		varchar(254) not null /* Expected absolute path of the file */,
    primary key entry (id, localname),
    foreign key (id) references cg_job(id) on delete cascade
) type=InnoDB;


/*
 * Algorithm queue table. Used for scheduling purposes
 */
create table cg_algqueue (
    grid		varchar(254) not null /* Relevant grid name */,
    alg			char(128)    not null /* Algorithm (executable) name */,
    batchsize		int	     not null /* Maximum batch size */,
    statistics		text		      /* Statistics data */,
    primary key entry (grid, alg)
) type=InnoDB;
