#! /usr/bin/env python

import sys, logging, os
from optparse import OptionParser
from ConfigParser import RawConfigParser

from soaplib.wsgi_soap import SimpleWSGISoapApp
from soaplib.service import soapmethod
from soaplib.serializers.primitive import String, Integer
from cherrypy.wsgiserver import CherryPyWSGIServer

from G3Bridge.G3BridgeMonitor import G3BridgeMonitor

parser = OptionParser(usage = "%prog [options]")
parser.add_option("-c", "--config",
                  help = "configuration file to use",
                  metavar = "FILE",
                  default = "/etc/3g-bridge.conf",
                  action = "store",
                  dest = "config")
parser.add_option("-p", "--port",
                  help = "port to listen on",
                  metavar = "PORT",
                  type = "int",
                  action = "store",
                  dest = "port",
                  default = "8080")

options, args = parser.parse_args();

config = RawConfigParser()
config.read([options.config])

# Set the log level
try:
    levelstr = config.get("defaults", "log-level")
    level = eval(levelstr, logging.__dict__)
    logger = logging.getLogger("")
    logger.setLevel(level)
except:
    pass

# Run the service
server = CherryPyWSGIServer(('0.0.0.0',options.port),G3BridgeMonitor(config))
try:
    server.start()
except KeyboardInterrupt:
    raise SystemExit("Interrupt caught, exiting")
